import 'public/global.css';
import { ChakraProvider } from "@chakra-ui/react"

export const metadata = {
  title: 'YoutubeSoundFlex',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link
          rel="icon"
          href="/icon.svg"
        />
      </head>      
      <body>
        <ChakraProvider>
          {children}
        </ChakraProvider>
      </body>
    </html>
  )
}
